before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/go64
    id: "go64"
    binary: "go64"
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy={{.Env.GITHUB_WORKFLOW}}/{{.Env.GITHUB_RUN_ID}}
      - -X main.binName={{.Binary}}
    env: []
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: bin
    format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  - id: tar
    format: tar.gz

checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256

snapshot:
  name_template: "snapshot"

changelog:
  sort: asc
  filters:
    exclude: []