
name: release

on:
  push:
    tags:
    - '*'

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    env:
      GO_VERSION: 1.19

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
