on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.19
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Gofmt
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then gofmt -d . && exit 1; fi

      - name: Go mod download
        run: go mod download

      - name: Go Vet
        run: go vet ./...

      - name: Go Build
        run: go build ./cmd/...

      - name: Go Test
        run: go test ./...
